FROM nginx:alpine
WORKDIR /var/www/metrics_service
COPY frontend/ .
COPY devops/conf/nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN chown -R nginx:nginx /var/www/metrics_service
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]